### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by blumysden** [zachleat/Humane-Dates#1]
Hi Zach,

Just found this script; it looks great.  (Also just found your blog for the first time, which I'm really enjoying.)  Just wanted to bring to your attention an error thrown by the Google Closure Compiler while I was trying to compile this together with some other scripts of mine:

ERROR - Parse error. Internet Explorer has a non-standard intepretation of trailing commas. Arrays will have the wrong length and objects will not parse at all.

This is from the end of the "formats" array.  I generally remove trailing commas like this in my own code for the reason Closure Compiler cites.  Don't know, of course, if you have a reason for leaving it in, but if not I thought you might like to know.

Thanks again for all the neat code you're putting out there.

**Comment by zachleat** [comment]
Closed by 65f7513109768e950a40aeb04104c7b5dddeaebf

**Comment by zachleat** [comment]
Doh! It was simply an oversight. Thanks for reporting!

**Comment by blumysden** [comment]
You're very welcome.  Glad to help.
